---

- name: Make sure a service is running
  systemd:
    state: started
    name: "docker"
    enabled: yes
  tags: backend

- name: Starting backend 
  docker_container:
    name: backend
    image: "{{ registry_ip }}:{{ registry_port }}/backend:{{ backend_version }}"
    restart_policy: always
    state: started
    restart: yes
    pull: yes
    ports:
      - "0.0.0.0:{{ backend_port }}:{{ backend_port }}/tcp"
    env:
        JAVA_OPTS: "--spring.datasource.username={{ db_user }}
		    --spring.datasource.password={{ db_pass }}
		    --spring.datasource.url=jdbc:postgresql://{{ db_ip }}:{{ db_port }}/{{ db_name }}
		   "
  tags: backend

